### ISSUE TITLE
Compatibility issue: --extra=f implies --file-scope=no

### ISSUE THREAD

**Issue by gstavi** [universal-ctags/ctags#1085]
In original ctags the command line:
ctags --extra=f -R .
Used to collect all tags including static and filenames.
Now it will not collect statics. This is since universal ctags added new extra flag 'F' for that and once extra is observed all extra flags are cleared to FALSE.
Obviously it can be fixed by adding explicit --file-scope=yes or by modifying the --extra flag parameter but it breaks existing scripts for tag generation.
It is also not mentioned in --help documentation.

Regards,
Gur

**Comment by masatake** [comment]
Thank you for reporting this.

I should write about this incompatibility both ctags.1 and  `--help` output.

I will force this incompatibility to users. Could you use `--extra=+f` instead of `--extra=f` ?

**Comment by gstavi** [comment]
I already fixed my script.
The question is how quickly less experienced users will understand the problem in case their system switch from old ctags to universal-ctags. Compatibility is really important to keep.

I think it would be better if extra options will be reset to their default values rather than to FALSE.
To make file scope usable via 'extra' you may add some new extra flag for '--file-scope=no'. E.g. 'g' for "Global only". That way "ctags --extra=f" will be compatible and whoever want the other behavior could use "ctags --extra=fg".

**Comment by masatake** [comment]
> I think it would be better if extra options will be reset to their default values rather than to FALSE.
To make file scope usable via 'extra' you may add some new extra flag for '--file-scope=no'. E.g. 'g' for "Global only". That way "ctags --extra=f" will be compatible and whoever want the other behavior could use "ctags --extra=fg".

The semantic is a bit complicated for me. But I wolud like to get more comments from you...

**Comment by masatake** [comment]
@gstavi, I have always compatibility issues. How, about adding global `--compatible-mode` option ?

**Comment by gstavi** [comment]
--compatible-mode parameter will not help old scripts that does not have it.

Quoting from the original ctags man page:
> If flags is preceded by either the '+' or '-' character, the effect of each flag is added to, or
> removed from, those currently enabled;
> otherwise the flags replace any current settings.

Previously none of the "--extra" related to the same option as another parameter in the command line.
Now '--extra=F' relates to the same option as --file-scope. And their default values are opposite. The default value of an absent --file-scope is to include statics while the default value of an absent --extra=F is to exclude statics.

If instead of having 'F' extra flag with semantics of --file-scope=yes (and absent semantics of --file-scope=no) we would have had a global-only 'o' extra flag with semantics of --file-scope=no (and absent semantics of --file-scope=yes) then the defaults would have matched.

Obviously having both 'F' and 'o' flags is another problem.
So if this solution is accepted 'F' should be obsoleted. The code may still acknowledge it as "NOT o" but it should be removed from documentation and discouraged.

A simpler non-compatible solution will be to change the default value of --file-scope to 'no' and document it.

I didn't test parameter ordering issues. Does the following produce the same results?
- ctags --extra=f --file-scope=yes
- ctags --file-scope=yes --extra=f

**Comment by masatake** [comment]
I'm sorry for this late response.
Instead of changing the code, I wrote about the incompatibility in man/ctags-incompatiblity.7.rst.in:

```
Unexpected synchronization between ``--file-scope`` option and "F/fileScope" extra
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Universal-ctags introduces "F/fileScope" extra as the alternative to
``--file-scope`` option.

Providing the two way to control the same thing in Universal-ctags
internal can cause a trouble.

A user, expecting "--file-scope=yes" is enabled by default, gives
"--extras=q". The intention of the user may be just enabling
"q/qualified". However, "--extras=q" is evaluated as "disabling all
extras including F/fileScope, then enabling only
q/qualified". Unexpectedly the command line becomes as if
"--file-scope=no" is set.

In this case the user should set "--extras=+q" instead of "--extras=q".
```

I would like to close this one that must be solved for releasing.
If you think I should write this topic more in the man page, could you make a pull request for the page?

**Comment by b4n** [comment]
@masatake I think the question is how compatible we are or wanna be with other/older CTags implementation (including Exuberant-CTags).

IIUC the issue here is that a set of options that work for both Exuberant and Universal CTags provide different results, which leads to user confusion.
Now the question is whether the incompatibility is worth it or whether we should avoid it to make it easier on users. Some pros and cons I can think of from the top of my head:
* Incompatibility might push users away (higher entry barrier, feeling that Universal-CTags is buggy, etc.)
* Incompatibility allows to fix some existing issues (consistency issues, usability issues, etc.)
* Incompatibility with a (de facto) open standard fights competition and innovation (unless the de-facto standard is itself blocking innovation)

In the end, I would think it boils down to 2 things: how important is compatibility, and how problematic it is. It's important to be compatible in some area because `ctags` is a historic command that is used a lot; so a new implementation of it should maintain reasonable compatibility to be used as a drop-in replacement. However, if we became the only `ctags` implementation, we might be able to afford changing stuff *if it has enough value*; but we should **not** introduce arbitrary incompatibilities in a dominant position, as it would push competition (and thus innovation) away -- and we luckily ain't in a market war and need to kill competition for profit.

**Comment by masatake** [comment]
@b4n, thank you for the comment.

Till releasing 6.0, about the command line interface, I would like to introduce arbitrary incompatibilities as much as possible if I think they are really needed for the future develoment of ctags. However, as far as I can remember the incompatiblity about this issue and the "~/.ctags.d" issue are the biggest ones.

I follow the rule I introduced:
(1) Describe the incompatiblity in ctags-incompatiblities.7 man page,
(2) Don't introduce ambiguous incompatiblities.

I had wrote an entry for this issue in ctags-incompatibities.7.
However, I think I violatge the rule (2); `--file-scope` still can be used in Universal-ctags.
I must remove `--file-scope`. So people can know the incompatibility easily.

 I must write the reason why the concept `file scope` should be managed/controlled with `--extras` option.

I would like to simplify the options controlling a parser. As the result of 3 years efforts, the options are simplified as follows:

* kinds related options,
* fields related options,
* extras related options,
* roles related options, and
* params related options.

I hope I don't have to anything more in the list after releasing 6.0.

The main part of ctags passes option settings specified by a user passes directly to parsers.
The API for parsers receiving the option settings are mostly fixed in conceptual level. ( I have to improve and change naming level things in the future.)

A parser doesn't have to use the other APIs to access an option settings; unlike Exuberant-ctags, no parsers in Universal-ctags accesses `Options` global variable directly.

The APIs (kind, fields, etc) is for separating the main part (of command line processing) from the parsers.
I thought the separation is important for the future of ctags. As the result u-ctags could not be the drop-in replacement for e-ctags.

Users may not satisfy with my policy. However, I don't take care how users say much. What I really take care is how parser developers say. I think parser developers extends the life of ctags.

I have to work more for the separation. However, in 6.0, I focused on the areas that have impacts on the command line users.

Sorry for non-summarized comment.

**Comment by masatake** [comment]
... I'm afraid I'm going wrong.

I wonder '--file-scope' should be represented/controlled in an extra flag.
Instead, introducing ``--scope=`` option will be better.

Let's consider following input:
```
int globalv;
static int filev;
static void filef (void)
{
}

void globalf (int paramv)
{
    int localv;
}
```

`--_scope=+{global}` (or `--_scope=+g`) is for capturing `globalv` and `globalf`.
`--_scope=+{file}` (, `--_scope=+f` or --file-scope=yes) is for capturing `filev` and `filef`).
`--_scope=+{local}` (or `--_scope=+l`) is for capturing `localv`.
`--_scope=+{parameter} (or `--_scope=+p`) is for capturing `paramv`.

About C language, this looks good idea for me if I can ignore the existing kinds in C parser.
C parser already defines parameter kind and local kind.

ctags already defines protection: field. We can extend the field to support the scope classes, global, file, local, and parameter.

I have to think about this idea more. 
Replacing `--file-scope=yes` with `--extras=+F` is not good for implementing this idea (`--scope=` option) in the future.

**Comment by masatake** [comment]
The concept of --_scope may be difficult to implement because it is up to languages and parsers.
As the name implies, ctags might be designed for C language originally. --file-scope is strongly coupled with the static modifier of C. My experience about ctags deveopment is not enough for abstracting the concep of --file-scope to implementing ``--_scope`` .
