### ISSUE TITLE
whiespace prefixed tags and orders in tags file

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#1141]
```
[yamato@x201]~/var/ctags-github% cat /tmp/foo.html 
cat /tmp/foo.html 
<h1> ABC</h1>

[yamato@x201]~/var/ctags-github% ./ctags /tmp/foo.html 
./ctags /tmp/foo.html 
[yamato@x201]~/var/ctags-github% cat tags 
cat tags 
 ABC    /tmp/foo.html   /^<h1> ABC<\/h1>$/;"    h
!_TAG_FILE_FORMAT   2   /extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED   1   /0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR    Universal Ctags Team    //
!_TAG_PROGRAM_NAME  Universal Ctags /Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL   https://ctags.io/   /official site/
!_TAG_PROGRAM_VERSION   0.0.0   /25bad34/
```

Look at the whiespace before `ABC`.

If a tag name is started with a whitespace, it is printed in tags file before pseudo tags.
I guess this behavior make client tools get into crazy.

Could you give me comment and ideas what we can do?

(Please change the tile of this issue if you can find better one.)

**Comment by jtanx** [comment]
+1 to fixing this; all parsers that generate whitespace prefixed tags should be fixed to not have leading/trailing whitespace in the tags (who searches for a tag including the leading/trailing whitespace?)

For some reason, I'm also seeing that it's sometimes failing to output any pseudo tags at all.

In both cases, this causes the ctags parser to be very slow (it has to do a sequential search over the whole file), because it can't detect that it's a sorted tags file.

**Comment by masatake** [comment]
Thank you for giving the comment.

**Comment by masatake** [comment]
```
<h3><a name="Summary">
Summary</a></h3>
```
html parser generates " Summary"  for this.

If the input is
```
<h3><a name="Summary"> Summary</a></h3>
```

making " Summary" is still acceptable though people may object to.

However,

```
<h3><a name="Summary">
Summary</a></h3>
```

In this case, just making "Summary" is enough, " Summary" is not needed.

I will work on this.

@jtanx, which kind of input file do you get the the trouble of the prefixed white space?

Basically I think ctags should  pass raw information of the original input file to client tools.
So I wonder what I should do about this issue.
