### ISSUE TITLE
Manual: --fields-LANG is not present in the man page

### ISSUE THREAD

**Issue by pragmaware** [universal-ctags/ctags#1183]
The --fields-LANG option is not present in the manual page.
Moreover, we have --LANG-kinds, I wonder why it's --fields-LANG and not --LANG-fields.

**Comment by masatake** [comment]
> The --fields-LANG option is not present in the manual page.

Yes, I know.

As you may know I introduced the option as an experimental feature.
When introducing the option, I wrote a section in docs/news.rst (http://docs.ctags.io/en/latest/news.html#parser-own-fields) .  If we think the feature is acceptable and stable enough,
we should update the man page. This process, writing docs/*.rst then updating man page, is standard workflow to maintain in the documents about u-ctags. 

> Moreover, we have --LANG-kinds, I wonder why it's --fields-LANG and not --LANG-fields.

Do you think the order, LANG, kinds, is really odd?

e-ctags has only --LANG-kinds. I added --kinds-LANG. I added --fields-LANG.
I have considered the behaviour of shell completion; when pressing tab at `--`, the terminal the user using may be filled with `--LANG` items because we have too many parsers. I don't want this behaviour.

I don't have time to write completion rule yet. However, I expect I can write rules implementing following behaviour: when pressing tab at `--`, `--kinds-`, `--fields-`, `--params-` are listed. When the user chooses one of them(`--kinds-` for example) and then presses tab again, the shell lists the languages supported by u-ctags.

The completion rules help ctags users in two aspects. It saves typing.  It helps users remember the name of options. For our user, the later one may be more important because they may forget concepts of u-ctags like `kinds`, `fields`, `extra`, etc.  

 For the above reason I would like to remove --LANG-kinds. I would like to provide --kinds-LANG only.
However, removing it causes a compatibility issue.

--regex-LANG is in e-ctags. This is good. I guessed if --regex-LANG is acceptable, --kinds-LANG, -fields-LANG, --extra-LANG(not imlemented), --param-LANG, etc will be acceptable.

**Comment by pragmaware** [comment]
Ow.. my fault: I overlooked --kinds-LANG.
So this is fine, as long they are all coherent.

As for the man page, yep, we should probably start updating it as otherwise features will probably "overflow" and we'll miss some of them. Filling up the man page will also give us a general overview of how the commandline looks now and tell if something needs to be adjusted.

**Comment by pragmaware** [comment]
So I close this.
