### ISSUE TITLE
Doesn't detect a symbol from NSPR

### ISSUE THREAD

**Issue by lvc** [universal-ctags/ctags#1225]
Hello,

The ctags tool doesn't detect PL_ClearArenaPool function in the code (nspr 4.13.1, include/nspr/plarena.h):

    PR_EXTERN(void) PL_ClearArenaPool(PLArenaPool *pool, PRInt32 pattern);

This command returned empty output:

    ctags -x --c-kinds=fpvx -I PR_EXTERN=extern include/nspr/plarena.h| grep PL_ClearArenaPool

But old parser works fine:

    ctags -x --languages=+OldC --language-force=OldC --OldC-kinds=fpvx -I PR_EXTERN=extern include/nspr/plarena.h | grep PL_ClearArenaPool
    PL_ClearArenaPool prototype   282 include/nspr/plarena.h PR_EXTERN(void) PL_ClearArenaPool(PLArenaPool *pool, PRInt32 pattern);

Is it Ok to use old parser? Will it be removed someday?

Thank you.

**Comment by b4n** [comment]
You can use `-I PR_EXTERN+=extern`, that will work (but won't see the return type).
However, there is now a more powerful preprocessor through `-D`: in this case, the best fix is `-D 'PR_EXTERN(x)=extern x'`.  The parser will really see `extern void PL_ClearArenaPool(…`, rather than the invalid `extern (void) PL_ClearArenaPool(…` or some other variants.

**Comment by pragmaware** [comment]
Yep, -D 'PR_EXTERN(x)=extern x' should work.

**Comment by lvc** [comment]
Verified with 6e839be606cbc750e6e6a7e6d16fe375adbef5ca. Works well.

Thank you.
