### ISSUE TITLE
HTTPS is broken for ctags.io

### ISSUE THREAD

**Issue by danobi** [universal-ctags/ctags#1266]
I didn't find any existing issues about this after a quick search. Please see attached picture:
![ctags https](https://cloud.githubusercontent.com/assets/824615/21771500/31aa87c2-d64d-11e6-9d50-0bedc663dd19.PNG)

**Comment by masatake** [comment]
@cweagans, could you look at this?

**Comment by cweagans** [comment]
It's been broken for a while, I think. I'll take a look.

**Comment by cweagans** [comment]
Actually, this was a new problem. Looks like it's because I changed DNS providers. I've resolved this, but it's waiting on DNS propagation. Closing for now, but feel free to reopen if this error doesn't go away within 24 hours.

Note that I'll be moving the site to my server so that we can have true HTTPS (right now, the connection between Cloudflare and Github isn't secure, so that could still be MITM'd pretty easily).

**Comment by masatake** [comment]
Thank you.
