### ISSUE TITLE
Unicode parse incorrect!

### ISSUE THREAD

**Issue by kendling** [universal-ctags/ctags#1275]
See the result tags file.
![screenshot_20161226_094605](https://cloud.githubusercontent.com/assets/3919496/22099569/dbd5e6c6-de66-11e6-9362-63be8d36fbf7.png)

The simple example header file.
[a.zip](https://github.com/universal-ctags/ctags/files/716057/a.zip)

**Comment by masatake** [comment]
Sorry but Universal-ctags may not support multi-byte strings.
However, about the input, `--pattern-length-limit` option may help you:

```
ctags --pattern-length-limit=200 -o - a.h 
SIZE_DROP_LEFT_ALL	a.h	/^    SIZE_DROP_LEFT_ALL = -1, \/\/ 丢弃后序所有内容，同时也取消接收完成失败的通知$/;"	e	enum:xxx
xxx	a.h	/^enum xxx {$/;"	g
```

**Comment by hexchain** [comment]
Any plan to support multi-byte strings?

**Comment by masatake** [comment]
> Any plan to support multi-byte strings?

I will not reject the contribution for supporting multi-byte strings  but I will not work on it.

**Comment by kendling** [comment]
Hi Masatake,

  Thanks for your reply, I will try the parameter for my repo.


Kend - vNet Studio
http://MyvNet.com

2017-01-22 10:32 GMT+08:00 Masatake YAMATO <notifications@github.com>:

**Comment by b4n** [comment]
A poor man's check could be not to split on bytes passing `(byte & 0x80) == 0x80`, which matches UTF-8 sub-bytes.

Maybe something like this for cutting (untested, just from the top of my head):
```C
if (max_len < line_len)
  {
    size_t i = 0;

    do
      {
        if ((line[max_len + i] & 0x80) != 0x80)
          break;
        i++;
      }
    while (i < 4; max_len + i < line_len);

    line[max_len + i] = '\0';
  }
```
Of course it's wrong, but it should avoid cutting UTF-8 sequences in the middle, which likely would avoid most cases.  If people use UTF-8.

**Comment by b4n** [comment]
@hexchain
> Any plan to support multi-byte strings?

It would be great especially as languages are getting more and more crazy allowing Unicode identifiers (seriously, I still don't understand how this isn't a toy, but whatever).

However, it's a *complex* task. It's not trivial to convert (but there generally are system libraries to do it), and it's close to impossible to properly guess the encoding.  If it's only not to cut in the middle of byte sequences, it's likely "fairly easy", but encoding support should probably rather stream some normalized format (UTF-8!!  or maybe Unicode code points) to the parsers so they don't themselves have to handle different stuff, and that means *correctly* detecting the input encoding, not simply something that looks compatible -- especially if we want to be able to generate one single encoding in the tags file rather than convert back.
