### ISSUE TITLE
'ctags: cannot open temporary file : File exists'

### ISSUE THREAD

**Issue by Yggdroot** [universal-ctags/ctags#1377]
On windows:
if run `ctags -n -u --fields=Ks  -f- aaa.cpp` for many times, this error occur.
The file name is different every time.
How can this be fixed?

**Comment by masatake** [comment]
Thank you for reporting this.

I don't have an access to Windows machine. So I have to know the situation more.
I would like to know the phrase "for many times".

What did you do the actually?
Do you mean running the same command line  simultaneously?

**Comment by Yggdroot** [comment]
Oh yes, run the same command for different files  simultaneously.
I did not test it on Linux, maybe there is the same issue.

**Comment by masatake** [comment]
One more question. Which platform do you use? I would like to know how do you build the binary.

> I did not test it on Linux, maybe there is the same issue.

As far as I know the way to handle temporary files in u-ctags is different between GNU/Linux and Windows.

**Comment by Yggdroot** [comment]
The windows 10, x64.
I used `make -f mk_mingw.mak` to build the binary.

**Comment by masatake** [comment]
Thank you. I will try to fix it.

**Comment by masatake** [comment]
I read http://docs.ctags.io/en/latest/windows.html#building-ctags-from-the-command-line . 
I guess you are using msys.
On msys, ctags ues tmpnam library function. The number of temporary files what can be created with tmpnam function has a limit. See http://www.cplusplus.com/reference/cstdio/TMP_MAX/.
If tmpfile library function can be used on msys, ctags should use it. I don't know whether it is possible or not.

There is a reason I myself don't try to let ctags on mysys use tmpfile; on msys2 ctags may use mkstemp which has no such limit as tmpnam.

You have two choices:
1. changing your platform from msys to msys2, or
2. hack tempFile function in main/routines.c to use tmpfile library function instead of tmpnam, and make a pull request:-P.

@k-takata san, do you have any comment or hint?

**Comment by Yggdroot** [comment]
I find the program run into this branch in main/routines.c:
```c
    #elif defined(HAVE_TEMPNAM)
    	const char *tmpdir = NULL;
    # ifdef WIN32
    	tmpdir = getenv ("TMP");
    # endif
    	if (tmpdir == NULL)
    		tmpdir = TMPDIR;
    	name = tempnam (tmpdir, "tags");
    	if (name == NULL)
    		error (FATAL | PERROR, "cannot allocate temporary file name");
    	fd = open (name, O_RDWR | O_CREAT | O_EXCL, S_IRUSR | S_IWUSR);
```
so tempnam() is called.
The [manual](http://www.ms.sapientia.ro/~lszabo/oprendszer1/man_en/htmlman3/tempnam.3.html) and [manual2](http://man7.org/linux/man-pages/man3/tempnam.3.html) say that "`Never use this function. Use mkstemp(3) or tmpfile(3) instead`".

**Comment by masatake** [comment]
Yes, I would like to remove code related to msys.
I would like to focus on msys2.

Anyway I should talk about Windows because I have too few knowleges about it.
I have to find active Windows developers till releasing ctags-6.0.

**Comment by k-takata** [comment]
If you use MinGW-w64/MSYS2, I recommend you to use autotools-based build system.
Using `mk_ming.mak` is a handy way, but it is mainly for old MinGW/MSYS1 and it doesn't detect new functions like `mkstemp`.
I'm not sure if there are needs for MinGW-w64 without MSYS2.

However, there is a question.
I think temporary files are deleted when ctags ends. Then why `tempnam` reaches the limit?
The temporary files are not deleted, or many ctags instances are executed simultaneously?

If the former case, I think it should be fixed.
If the latter case, maybe we should implement our own `mkstemp` for Win32 because MSVC might also have the same problem.

I have implemented `tmpfile` in another project:
https://github.com/k-takata/lv-mod/blob/ba8350d544f241eae16b3b4c1efeea2e7f1edc88/src/stream.c#L70-L122
A similar implementation might be needed.

**Comment by masatake** [comment]
@k-takata san, thank you.
> many ctags instances are executed simultaneously?

I guessed so.

**Comment by Yggdroot** [comment]
I executed no more than 50 ctags commands simultaneously, so I don't think the limit has been reached.
In my opinion, the implementation of tempfile methods is not thread-safe or process-safe.

**Comment by k-takata** [comment]
Ah, now I understand.
`tempnam` just generates a new temp filename, and it can generate the same name for different processes.
Ctags processes try to open with the filename, and the second process will fail.

**Comment by k-takata** [comment]
I think we can copy the implementation of `mkstemp` from MinGW-w64.

Source code:
https://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/mingw-w64-crt/misc/mkstemp.c

License:
https://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/COPYING.MinGW-w64/COPYING.MinGW-w64.txt
https://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/COPYING.MinGW-w64-runtime/COPYING.MinGW-w64-runtime.txt
(Not sure which license will be applied in this case.)
