### ISSUE TITLE
regex parser, wrong detection of type

### ISSUE THREAD

**Issue by tarzanek** [universal-ctags/ctags#1385]
Hi @masatake 

I had uctags from february and below worked well for "property Id" (it was detected as property, with recent head it's detected as procedure):

ctags options:
```
./ctags/ctags -f"-" --options=./ctags-pascal.options  Sample.pas
```
ctags-pascal.options file:
```
--fields=-anf+iKnS
--c-kinds=+l
--file-scope=yes
-u
--C++-kinds=+l
--langdef=pascal
--langmap=pascal:.pas
--regex-pascal=/([[:alnum:]_]+)[[:space:]]*=[[:space:]]*\([[:space:]]*[[:alnum:]_][[:space:]]*\)/\1/t,Type/
--regex-pascal=/([[:alnum:]_]+)[[:space:]]*=[[:space:]]*class[[:space:]]*[^;]*/\1/c,Class/
--regex-pascal=/([[:alnum:]_]+)[[:space:]]*=[[:space:]]*interface[[:space:]]*[^;]*/\1/i,interface/
--regex-pascal=/^constructor[[:space:]]+([a-zA-Z0-9_]+(<[a-zA-Z0-9_,]+>)?\.)([a-zA-Z0-9_<>,]+)[[:space:]]*/\1\3/n,Constructor/
--regex-pascal=/^destructor[[:space:]]+([a-zA-Z0-9_]+(<[a-zA-Z0-9_,]+>)?\.)([a-zA-Z0-9_<>,]+)[[:space:]]*/\1\3/d,Destructor/
--regex-pascal=/^procedure[[:space:]]+[a-zA-Z0-9_<>,]+\.([a-zA-Z0-9_<>,]+)[[:space:]]*/\1/m,procedure/
--regex-pascal=/^function[[:space:]]+[a-zA-Z0-9_<>,]+\.([a-zA-Z0-9_<>,]+)[[:space:]]*/\1/f,function/
--regex-pascal=/property[[:space:]]+([a-zA-Z0-9_<>,]+)[[:space:]]*/\1/p,property/
--regex-pascal=/(uses|interface|implementation)[[:space:]]*/\1/s,Section/
--regex-pascal=/unit[[:space:]]+([a-zA-Z0-9_<>,][a-zA-Z0-9_<>, ]+)[;(]/\1/u,unit/
```

Sample.pas file:
```
unit Sample;
uses
  User;

interface
  type
    TSample = class
    private
      FId : integer;
      FDescription : String;
      FUserId: integer;
      function GetId : integer;
      procedure SetId(const aValue : integer);
    public
      class function GetClassName: string;
      function GetIdAndDescriptionString: string; virtual;
      function GetUser: TUser;
    published
      property Id: integer read GetId write SetId;
      property Description: string read FDescription write FDescription;
    end;

implementation
uses
  Logging;

function TSample.GetId: integer;
begin
  Result := FId;
end;

procedure TSample.SetId(const aValue: integer);
begin
  FId := aValue;
end;

class function TSample.GetClassName: string;
begin
  Result := 'TSample';
end;

function TSample.GetUser: TUser;
begin
  Result := TUser.Create(FUserId);
end;

end.
```

**Comment by tarzanek** [comment]
Id      Sample.pas      /^      property Id: integer read GetId write SetId;$/;"        procedure       line:40

^ is wrong
it used to be before I updated my old trunk(~Feb 2017) to:
Id      Sample.pas      /^      property Id: integer read GetId write SetId;$/;"        property        line:40

any clues if this is a regression or the regexps are wrong?

thank you
L

**Comment by masatake** [comment]
pascal is already defined in ctags.
```
[yamato@master]~/var/ctags-github% ./ctags --options=NONE --list-kinds=pascal
ctags: Notice: No options will be read from files or environment
f  functions
p  procedures
```

Actually when I let ctags load your ctags-pascal.options, I got messages.
```
[yamato@master]~/var/ctags-github% ./ctags --options=NONE --options=./ctags-pascal.options
ctags: Notice: No options will be read from files or environment
ctags: Warning: Language "pascal" already defined
ctags: Warning: Don't reuse the kind letter `p' in a language Pascal (old: "procedure", new: "property")
ctags: No files specified. Try "ctags --help".
```

You reuse `p` for property. However, the build-in pascal parser use it as procedure.
Different from e-ctags, u-ctags forbids reusing of kind letter.

**Comment by tarzanek** [comment]
AH, ok , so this IS related to reuse of letters ... (I browsed the commits and wondered if this can be it)
(fwiw if you provide a file you won't see above message, so sorry for my ignorance and not noticing it in test logs)

So just a stupid Q so I understand the architecture - if the language is already defined and I redefine it, will I still inherit the language and have it with my additions ?
Is there a way to completely override internal definition of the language by custom regex? (just checking my options, I don't really want to do it)

**Comment by masatake** [comment]
Yes , an original kind can be extend with regex patterns.

Assume you want to capture a token next to `procedureExtra` which may appear in a pascal dialect pascalZ as a procedure:

input.pas:
```
procedureExtra myXproc ...
```

Here you want to capture myXproc which the built-in pascal parser cannot capture because it doesn't know the word `procedureExtra`. Extending by regex may help you.

u-ctags offers multiple ways.

1. the simplest add-hoc way

If you just want to capture `myXproc` as a procedure of pascal, do as follows:

```
--regex-pascal=/^procedureExtra[[:space:]]+[a-zA-Z0-9_<>,]+\.([a-zA-Z0-9_<>,]+)[[:space:]]*/\1/p/
```

As a kind just specifying `p` is enough because `p` is already defined in the built-in parser.

2. defining specialized kind
If you wan to capture `myXproc` as a language item in specialized kind of pascal, do as follows:

```
--kinddef-pascal=x,xproc,extra procedure
--regex-pascal=/^procedureExtra[[:space:]]+[a-zA-Z0-9_<>,]+\.([a-zA-Z0-9_<>,]+)[[:space:]]*/\1/x/
```

One of the policy in u-ctags devel, different things should be recorded different, don't unify too much things in ctags level. So introducing `x` kind and using it for procedureExtra are aligned to the policy.

However, you may wonder `x` is nerver conflicted with the kinds of built-in parser in the future.
u-ctags is actively developed. Therefore someone, maybe I, will introduce a kind using `x` as a kind letter.
You may not want such potential conflictual.

3. writing a subparser

```
--langdef=PascalZ{base=Pascal}
--kinddef-PascalZ=x,xproc,extra procedure
--regex-PascalZ=/^procedureExtra[[:space:]]+[a-zA-Z0-9_<>,]+\.([a-zA-Z0-9_<>,]+)[[:space:]]*/\1/x/
```

Here `x` is defined in PascalZ parser not in Pascal parser. Therefore the conflict never occurs.

----

There is no good way to overriding an existing parser completely.
Just turning off the original Pascal parser and write your own one with different name.

```
--languages=-Pascal
# clear the mapping
--map-Pascal=
--langdef=MyPascal
--map-MyPascal=+.pas
--kinddef-MyPascal=p,procedure,procedures
...
--regex-MyPaslca=.../p/
```

**Comment by tarzanek** [comment]
Thank you @masatake , this explains, will fix on our side as needed.
