### ISSUE TITLE
Can't get tags for __property keyword for C++Builder sources

### ISSUE THREAD

**Issue by FlKo** [universal-ctags/ctags#1499]
C++Builder extends C++ by adding "properties", e.g.
`__property int Hello = {read=FHello, write=FHello};`
which act similar to getter/setters.

Universal Ctags does not get tags for those lines although they are important public class members.
Adding `-D __property` to the command line doesn't do the trick.

**Comment by masatake** [comment]
It seems that `__property` is not a macro. I think it is a language level extension of C++Builder.
Therefore `-D` option may not be a solution. I guess C++ parser of ctags doesn't understand `{read=...` and `write=` for int typed member.

So you may have to write a C++Builder specialized parser based on C++.
In the following example, world is captured twice. Because the type of world is `struct ...`.
Therefore C++ parser of ctags can capture `world` as a member. Scope information cannot be
captured in CxxBuilder parser. It is limitation of current implementation of ctags.

```
[jet@localhost]~/var/ctags% cat /tmp/foo.cc 
cat /tmp/foo.cc 
class Foo {
  __property int Hello = {read=FHello, write=FHello};
  __property struct World world = {read=Fworld, write=Fworld};
};
[jet@localhost]~/var/ctags% cat c++builder.ctags
cat c++builder.ctags
--langdef=CxxBuilder{base=C++}
--kinddef-CxxBuilder=P,property,properties
--regex-CxxBuilder=/__property[ \t]{1,}.{1,}[ \t]{1,}([a-zA-Z_][a-zA-Z0-9_]*)[ \t]*=[ \t]*\{/\1/P/
[jet@localhost]~/var/ctags% ./ctags --fields=+lK  --options=c++builder.ctags -o - /tmp/foo.cc
./ctags --fields=+lK  --options=c++builder.ctags -o - /tmp/foo.cc
Foo	/tmp/foo.cc	/^class Foo {$/;"	class	language:C++	file:
Hello	/tmp/foo.cc	/^  __property int Hello = {read=FHello, write=FHello};$/;"	property	language:CxxBuilder
world	/tmp/foo.cc	/^  __property struct World world = {read=Fworld, write=Fworld};$/;"	member	language:C++	class:Foo	typeref:struct:World	file:
world	/tmp/foo.cc	/^  __property struct World world = {read=Fworld, write=Fworld};$/;"	property	language:CxxBuilder
[jet@localhost]~/var/ctags% 
```

**Comment by FlKo** [comment]
Many thanks, again!!
