### ISSUE TITLE
CMake parser

### ISSUE THREAD

**Issue by hadrielk** [universal-ctags/ctags#1816]
Hi, I've written a CMake files parser using the optlib multi-table regex options. It only tags basic things like build target names, cmake variables, cmake function names, etc. My questions are:

1. Is this something useful that you want?
2. If yes, should I create a PR for this repo, or the [ctags-xparsers](https://github.com/universal-ctags/ctags-xparsers) one?
3. Should I use optlib2c and include the generated C-code in the PR? Or should I just start with the `cmake.ctags` file and wait for feedback first?

Thanks!

p.s. I really appreciate the new multi-table regex stuff. With it we were finally able to create tags for things generated by C/C++ macros in my employer's codebase. Thank you!

**Comment by masatake** [comment]
Today is one of the most delightful day in my free software programming life.
As far as I can remember, other than I, you are the first person who uses the multi-table regex feature.
I'm suppressed at there is a person who can use it because the feature is not documented enough.
I guess you read my puppetManifest.ctags.  Any comment for the feature itself and pull request for its documents are really welcome.


> Hi, I've written a CMake files parser using the optlib multi-table regex options. It only tags basic things like > build target names, cmake variables, cmake function names, etc. My questions are:
> 1.  Is this something useful that you want?

YES. Do you know I implemented the multi-table regex feature was for writing cmake parser?
After implementing the feature, I had to read puppet manifests in my day job. So I changed the
target to puppet manifets. "writing cmake parser" has been in my queue. It seems that I can dequeue the item:) In addtion, I think build-scriptts are the important area for u-ctags. cmake becomes popular, so we need a parser for it.

> 2. If yes, should I create a PR for this repo, or the ctags-xparsers one?
Please, forget ctags-xparsers repo. When we started this project, I expected we get many parsers written with `--regex-<LANG>` option. At that time we don't have optlib2c translator. So I have a plan to distribute
.ctags files in a package separated from ctags itself. ctags-xparsers was planed as a place to maintain separated .ctags files. Now we have the translator so we don't need the separate repository.
Please, make a pull request for this repo.

> 3. Should I use optlib2c and include the generated C-code in the PR? Or should I just start with the cmake.ctags file and wait for feedback first?

Please, add generated C-code, too. When I merge your change, the C-code must be included.

> p.s. I really appreciate the new multi-table regex stuff. With it we were finally able to create tags for things generated by C/C++ macros in my employer's codebase. Thank you!

Could you tell me if you have a trouble or difficulties during writing .ctags file?
So I can improve http://docs.ctags.io/en/latest/optlib.html?highlight=mtable.

**Comment by hadrielk** [comment]
> I guess you read my puppetManifest.ctags.

Actually, no when I wrote the C++ macro expansion one I just read your [Extending ctags](http://docs.ctags.io/en/latest/extending.html) section of the docs, so I had to do a lot of trial and error to get it working right. The `-V` verbose output you print is *really* useful for doing that, and is really great.

It's only when I wrote the `CMake` one that I went to look at the ones already in the `optlib` directory and discovered things like `–_mtable-extend-`. 😄 

> Please, add generated C-code, too. When I merge your change, the C-code must be included.

OK, I'm writing the Units tests now. I like how simple it is to write them too!

> Could you tell me if you have a trouble or difficulties during writing .ctags file?

I'll try to remember the issues I had, and submit a PR to update the docs in a few days. (it's the least I can do to repay you for adding this feature set!)

The biggest amount of time I spent on it though wasn't in the logic, but in optimizing performance. In my day job I work on a code base with slightly more than 9k files, and 300k lines of C/C++ code. About half of that is third party code. Without any options, `ctags` takes me less than 5 seconds to scan them all and generate ~260k tag lines. With my first iteration of an optlib file using the multitable regex to handle our code-generating macros, I ended up killing `ctags` after about 2 **hours**. It wasn't broken or in a loop - it was just *really* slow. It took me a while, but eventually I got it down to ~10 **seconds**.

For the CMake one, we have ~350 CMake files of ~27k lines, from both us and third party libraries. the first iteration of the option file took ~60 seconds to scan those files and generate 1200 tag lines. (just the CMake files, nothing else) After some trial and error it's down to ~8 seconds. Much of that is now just in file/directory handling overhead I think, because combined with the macro one the total is now ~15 seconds.

BTW, at one point I even tried your `--_parallel` branch changes from your personal repo, just to get the time down. On my machine (a MacBook Pro) it was ~3x faster in parallel, compared to running non-parallel `ctags -f - ... | sort > file`. But my machine has a very fast SSD drive; I'm not sure how it would do on a spinning disk and in a VM or container.
