### ISSUE TITLE
Python: type hints (Was: CTags Issue in Geany IDE)

### ISSUE THREAD

**Issue by DevynCJohnson** [universal-ctags/ctags#1867]
When applying [PEP484](https://www.python.org/dev/peps/pep-0484/) (Type Hints) to variables, the list of "symbols" (in the symbol box in the Geany IDE) in the current file no longer displays the variables using type hints. The parser should be modified to recognize Python symbols using the format VARIABLE: TYPE = VALUE, rather than just VARIABLE = VALUE.

It [was suggested by the Geany developers](https://github.com/geany/geany/issues/1943) that I post my issue here.

**Comment by masatake** [comment]
It seems that ctags works fine even if the type hits are attached:
```
$ cat input.py 
# Taken from
# https://www.python.org/dev/peps/pep-0484/
def greeting(name: str) -> str:
    return 'Hello ' + name
$ u-ctags --kinds-Python=+z -o - input.py 
greeting	input.py	/^def greeting(name: str) -> str:$/;"	f
name	input.py	/^def greeting(name: str) -> str:$/;"	z	function:greeting	file:
```

Do you have any example input for that ctags doesn't work expectedly?

**Comment by b4n** [comment]
@DevynCJohnson report is a little misleading, because [PEP-484](https://www.python.org/dev/peps/pep-0484/) doesn't speak of annotating variables, which is introduced in [PEP-526](https://www.python.org/dev/peps/pep-0526/).

But in any case, our Python parser suppors both [PEP-3107](https://www.python.org/dev/peps/pep-3107/) (c.f. 60db69f094fa2c9c1647443b6a2b589e7c9bceb0, which is function annotation syntax used by PEP-484) and PEP-526 (d771a1e5276e1345bcfe03e3aebdce466cbd8d8e), so all should be covered.

If Geany doesn't support these it's just that it's behind in syncing with uctags -- actually, it doesn't have anything of the new and ehanced token-based parser. It's planned, though.

**Comment by b4n** [comment]
Please reopen if I missed something and we actually lack support for some of these in UCTags.

**Comment by masatake** [comment]
BTW, it will be nice if we can put `TYPE` to "typeref" field of a tag for `VARIABLE`.
