### ISSUE TITLE
Permission denied with --options

### ISSUE THREAD

**Issue by peara** [universal-ctags/ctags#2017]
I built ctags as in `https://github.com/universal-ctags/ctags-snap`
I'm using ctags with vim, so I have an option file under `/home/peara/.vim`
Running ctags produce this error:
```
ctags --options=/home/peara/.vim
ctags: cannot open option directory "/home/peara/.vim" : Permission denied
```
Further examination show that all directories with `.` in name will produce this error regardless of permission.
Is this a known bug? What can I do except moving option file to another directory?

**Comment by reaysawa** [comment]
I was just about to report this issue.

Snap install had permission errors happening for me, too. Furthermore it was **NOT** reading files from the default directory `~/.ctags.d`.

```
 ls -l /snap/bin/universal-ctags.ctags
lrwxrwxrwx 1 root root 13 Dec 19 12:46 /snap/bin/universal-ctags.ctags -> /usr/bin/snap
```

I also noticed I couldn't symlink this executable anywhere because it points to the snap binary.

---

Couldn't bother too much with it so I compiled the master code and it works.

http://inti.sourceforge.net/tutorial/libinti/autotoolsproject.html

> ./autogen.sh
> aclocal
> autoconf
> ./configure && make && sudo make install

**Comment by masatake** [comment]
If this is about snap, please, report the issue to https://github.com/universal-ctags/ctags-snap .

**Comment by masatake** [comment]
Please, don't refer to http://inti.sourceforge.net/tutorial/libinti/autotoolsproject.html. 

> ./autogen.sh
> aclocal
> autoconf
> ./configure && make && sudo make install

This is NOT the instruction for building Universal-ctags.
See https://github.com/universal-ctags/ctags/blob/master/docs/autotools.rst .

Now network connection is needed to build ctags because git submodule is run in autogen.sh.

**Comment by masatake** [comment]
@bboymimi, could you look int this?

**Comment by masatake** [comment]
If the issue is reproduced even with an executable built with directly with autotools, please, open a new issue.
If the issue is reproduced only with snap, report it to ctags-snap.
