### ISSUE TITLE
RPM package won't be created

### ISSUE THREAD

**Issue by nenadalm** [universal-ctags/ctags#230]
according to the help: https://github.com/fishman/ctags/blob/cfffbcf2c574fa391672a7dc5443d76735e049c3/maintainer.mak#L208

I've tried to create tarball using https://github.com/fishman/ctags/pull/183 and then rpm:

``` shell
$ autoreconf
$ ./configure
$ make
$ make dist
$ cp ctags-da56977.tar.gz /tmp/ctags/
$ cd /tmp/ctags
$ tar -xf ctags-da56977.tar.gz
$ cd ctags-da56977
$ make -f maintainer.mak release-rpm-2.5
```

and it told me:

```
make: *** No rule to make target `release-rpm-2.5'.  Stop.
```

(the same when I try to run the last command from the repository folder)

(it was told me that it has nothing to do with https://github.com/fishman/ctags/pull/183 so I created this separate issue)

**Comment by nenadalm** [comment]
```shell
$ make -v
GNU Make 3.82
Built for x86_64-redhat-linux-gnu
Copyright (C) 2010  Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by cweagans** [comment]
We should strip the RPM packaging stuff (and pretty much everything else related to packaging) out of the repository. Maintaining packaging scripts should not be our responsibility, especially given that all of the other downstream packaging folks I've talked to said that even if we include packaging scripts, they won't use them because they maintain their own scripts separate from ours.

We *might* want to keep the spec file, since there's some copy in there that we'll want to use, but that's about it.

**Comment by vhda** [comment]
The only reason why I would like to keep these files is to allow a knowledgeable user to use his distro's package instead of manually installing with `make install`. But then again, with the proliferation of PPAs and other alternatives this might not be so important nowadays.

This is just an opinion, I will not oppose that we remove the files because keeping them just means we'll need to also include testing package creation in travis-ci.

**Comment by cweagans** [comment]
@vhda, that's not the case at all. I don't want people to have to use `make install` either, but other people have volunteered to package Universal Ctags for their distro. Right now, we have commitment from Debian, Arch, and Gentoo. I'm reaching out to the RHEL/Fedora package maintainer for Exuberant Ctags to see if he'll either switch to Universal Ctags or at least package Universal Ctags in addition to Exuberant Ctags. A common reply from all of the packagers, however, is that they won't use the packaging scripts that are in our repo. They have their own.

The point is, we don't need to deal with it ourselves. Packaging will happen somewhere else.

**Comment by vhda** [comment]
Using Debian as an example, which is the distro I'm more comfortable with.
If I have Debian Stable installed, I will not have the latest version of ctags available. The package maintainer will keep updating it, sure, but it will compile it against Debian Testing/Unstable. Even for a small package like ours, it is possible that the maintainer will need to increase the version requirements of library dependencies, which in turn will make it harder to compile in Debian Stable.
There is a Debian Backports project that **may** have universal-ctags backported from Unstable to Stable, but it is not guaranteed.

So, if I want to grab the latest version of universal-ctags my only alternative is to "make install". If the debian folder is available I could simply run `dpkg-builpackage -b` and a .deb would be created!

(I'm oversimplifying here. There are other alternatives of creating a .deb package, but some are not that easy to use.

**Comment by cweagans** [comment]
@vhda See discussion in https://github.com/universal-ctags/ctags/issues/655. We don't need to do it. It's more for us to maintain, it's another thing that can break, etc. The packaging scripts that the debian maintainer will use are public, so if it's important that someone can get the bleeding edge version, we can just add a link to those scripts in the documentation. Someone that wants to build from HEAD can just do `make install`, as far as I'm concerned, though.
