### ISSUE TITLE
Merging patch sf.patch:77

### ISSUE THREAD

**Issue by Corax26** [universal-ctags/ctags#234]
[Patch #77](http://sourceforge.net/p/ctags/patches/77/) brings *major* bugfixes to c.c (mainly regarding local variables), both for C and C++, for this reason merging it should be considered high priority. I merged it about one year ago in my own repo and I haven't encountered any issue so far (at least no new issue).

However, the problem is that the changeset is rather big, adding some logic and heuristics to several parts of the parser. My question would be: is it acceptable to directly merge the patch (in a single commit), or is it necessary to split it in several commits?

Note that the author provided a test file (see [the linked archive](http://sourceforge.net/p/ctags/patches/_discuss/thread/2a3a8916/6741/attachment/ctags_cons_patch-20120531.tgz)), so at least it will be easy to add a test unit.

**Comment by steveno** [comment]
Both of the links you give result in a 404 for me.

**Comment by kopischke** [comment]
@steveno:

> The sourceforge.net website is temporarily in static offline mode.
Only a very limited set of project pages are available until the main website returns to service.

… should be temporary :).

**Comment by Corax26** [comment]
Yep: "The sourceforge.net website is temporarily in static offline mode.", and also:
<blockquote class="twitter-tweet" lang="fr"><p>There&#39;s instability and frequent 500 errors on the <a href="https://twitter.com/hashtag/SourceForge?src=hash">#SourceForge</a> site currently. We&#39;re working on getting this fixed ASAP.</p>&mdash; SF.net Operations (@sfnet_ops) <a href="https://twitter.com/sfnet_ops/status/565180532535730178">10 Février 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by masatake** [comment]
@Corax26, thank you for trakcing the bug and change.

I have two comments.

1. when submitting and merging changes, please, make their origin and author clear in commit log.
   See http://sourceforge.net/p/ctags/patches/1/
   We cannot pick this because its author is anonymous.

2. .b test
    You may know write how to write a test of Units.
    Could you write a test case for the bug, first?
    We can pick the existing fix (or fix from scratch) later.
    Could you use .b as suffix fot the test directory?
    With the suffix, travis may ignore the error.
    See docs/units.rst.
    
Thank you again.

**Comment by fishman** [comment]
seems to be this guy https://github.com/lyokha

**Comment by Corax26** [comment]
@fishman Indeed, let's mention him so that he can take part to the discussion @lyokha

@masatake Sure I can add a new unit, all I have to do is take the test from the archive.

**Comment by lyokha** [comment]
Hi guys. Yes, I did that patch some years ago :)

**Comment by Corax26** [comment]
@lyokha Cool, would you be interested in taking care of importing it into this repo? Since the official ctags repo is almost dead now (at least they haven't accepted any patch for ages), and considering that fishman's repo is probably the most active now, trying to import fixes and improvements from many other forks, it's probably the best way for other users to take advantage from your patch :)

**Comment by lyokha** [comment]
Ok, what shall i do for that? Fork / merge / pull request or just giving my OK for somebody else to do that?

**Comment by Corax26** [comment]
Well you can do either it's up to you :) If you're willing to do it yourself (i.e. fork/merge/PR), that's fine, otherwise I'm also fine with doing it myself.

I wonder, do you think the test file you provide (test.c) is complete enough? Thinking about it, your fixes should also apply to global variables, so it might be worth adding global variables to the test unit.

**Comment by lyokha** [comment]
Ok, I think that you'll do it better. :)

I made test.cpp to expose distinct differences between original and patched versions of ctags. I used

```sh
ctags --c++-kinds=+pl --fields=afmikKlnsStz test.cpp
```

and then compared results: you'll see many errors in original ctags. The patched ctags is not ideal too: variable ``x7`` is erroneously parsed as prototype (it is difficult to deduce it as a variable because it does not use literals or digits meanwhile using sole ampersands).

The fix must apply to global variables too: i made all tests inside main() without any special idea in mind: you may comment declaration of main() along with its curly brackets and get same result (only variables will be marked as ``variable`` instead ``local``).

**Comment by Corax26** [comment]
Okay then, I'm planning to first do a PR with a test unit based on your test.cpp but with the locals duplicated as globals, and I'll comment out the variable that still doesn't work with your patch (to avoid the unit still failing after I import the patch). Overall I think your heuristics definitely make sense, it's hard to distinguish a variable declaration from a prototype even for humans ([http://www.wikiwand.com/en/Most_vexing_parse](most vexing parse) anyone?) so the cases where the heuristics fail (like too many `&` for `x7`) are quite acceptable, and the patch is still a huge overall improvement :)

**Comment by masatake** [comment]
@Corax26, @lyokha, thank you for your efforts. It is nice to separate the patch and test case one by one for each bugs reported in sf.net.

**Comment by Corax26** [comment]
@lyokha About the patch, there is something that doesn't feel right. For the local variable `h1`, the current version gives a prototype with "int a = R" (strange, but anyway). Your version gives exactly the same result, but instead of a 'R', we get some illegal character, hex 0xD3 (8b ASCII). Do you know what's going on here?

**Comment by lyokha** [comment]
@Corax26 ``h1`` is really a prototype of a function with default value for its argument assigned. There is a comment in *test.cpp* before this, it says

```c++
    // prototype of the following function
    // will have STRING_SYMBOL character!
```

I remember that there a was a difficulty to deduce a correct prototype here, i'll look it again to find a possible way to do it.

**Comment by lyokha** [comment]
I made some investigations and found why retrieving a string prototype (and char prototype too) is difficult. It looks like originally in ctags there were no support for collecting strings and characters (i.e. texts surrounded by double and single quotes): they both are not needed in variable tags and in C-style prototypes which cannot refer to default values. That's why they were *optimized* on a very low level in function ``cppGetc()`` in get.c: all strings are replaced by a single character ``'S' + 0x80`` that corresponds to ASCII symbol *0xD3* . Prototypes are collected in function ``parseParens()`` in file c.c: very deeply it eventually calls ``cppGetc()`` functions but original string at this level is lost several steps ago.

Anyway i have a workaround: let's print ``<String>`` or ``<Char>`` instead ugly ``STRING_SYMBOL`` and ``CHAR_SYMBOL`` characters. Here is a quick and dirty patch against *patched* c.c for function ``skipToMatch()``: this should not break anything else because it applies only to collecting prototypes functionality.

```diff
--- c.c	2015-02-22 13:16:53.802475911 +0300
+++ c.c.new	2015-02-22 13:16:48.603651345 +0300
@@ -1377,7 +1377,20 @@
 	while (matchLevel > 0  &&  (c = skipToNonWhite ()) != EOF)
 	{
 		if (CollectingSignature)
-			vStringPut (Signature, c);
+		{
+			switch (c)
+			{
+				case CHAR_SYMBOL:
+					vStringCatS (Signature, "<Char>");
+					break;
+				case STRING_SYMBOL:
+					vStringCatS (Signature, "<String>");
+					break;
+				default:
+					vStringPut (Signature, c);
+					break;
+			}
+		}
 		if (c == begin)
 		{
 			++matchLevel;
```

(beware of tabs inside the patch! I want to follow original ctags coding style. Hmm, looks like they will be lost :( )

**Comment by Corax26** [comment]
Fair enough, I was wondering what the comment above meant by "STRING_SYMBOL" but now it all makes sense :p I think your modification is sensible, I'll take it into account when importing the patch (and I'll take care of the spaces vs tabs matter).

Also, `h1` is actually parsed as a function because it is followed by `{}`, since it is illegal in both C and C++ to define a nested function I'll remove them to actually make it a prototype (and I'll leave them for the corresponding global variable).

**Comment by lyokha** [comment]
ah, yes, this is a function :) But assigning string to an int is also illegal, unfortunately ctags is not able to typecheck.

**Comment by Corax26** [comment]
I'll mention it in a comment when I'm done, I'm currently modifying the test file to remove what is not legal C++ as far as possible (except some interesting cases like `ind d2( "a" * 2 );`); the rationale is that we want ctags to be as good as possible at parsing legal files, but I don't think that the result of parsing illegal expressions really matters (as long as ctags doesn't crash) ;)

**Comment by cweagans** [comment]
Sorry for the noise. Just switching the "Release blocker" tag for the "Initial release" milestone so that everything is tracked in one place.

**Comment by masatake** [comment]
@pragmaware, can I ask you to look at this ?
The code base is changed. So what we can do it taking ideas.

**Comment by pragmaware** [comment]
The test is present as unit parser-cxx.r/variables-prototypes.cpp.b .
The new parser already fixes most of the problems but not 100% of them.
This is because few of the lines are actually very ambiguous (could be interpreted both as variable or prototype depending on the actual meaning of the tokens inside and we'll probably never get them 100% right) and there are still some buggy corner cases. However, I'm working on fixing the corner cases and sooner or later we'll have that unit test passed. The patch comes from a totally different codebase and can't be merged at this point. So I'm closing this issue for now.

**Comment by masatake** [comment]
@pragmaware, thank you.

**Comment by Corax26** [comment]
@pragmaware Thanks for reviewing the patch, sorry to have given up on it... Glad to hear that most problems have already been addressed, the most ambiguous cases are very rarely encountered in real code anyway.
