### ISSUE TITLE
Version Confusion

### ISSUE THREAD

**Issue by ZweiEuro** [universal-ctags/ctags#2641]
My version:
```
Universal Ctags 0.0.0(a3c87ab5), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jan  7 2020, 22:54:55
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml, +packcc

```

What does this mean exactly?
I can't find any other version of "Exuberant Ctag" so I am guessing the package 
https://aur.archlinux.org/packages/universal-ctags-git/
is the most up to date?

But 
https://www.archlinux.org/packages/extra/x86_64/ctags/
links to the same pages... ?
What is the most up to date version? What is where the most updated or the most functional.

On top of that there is also a snap version.
https://snapcraft.io/install/universal-ctags/arch

As an arch user, I could install all three, which of these am I supposed to get if I want the most recent stable version that is as close as can be to the exuberant Ctags

**Comment by k-takata** [comment]
> Universal Ctags 0.0.0(a3c87ab5)

This is the version.
We haven't released Universal Ctags yet. So, the version number is 0.0.0 for years. We can only identify the precise version by its commit ID, in this case, a3c87ab5.

> if I want the most recent stable version

There are no stable versions. If you want a recent version, the best way would be to build ctags by yourself.

**Comment by alerque** [comment]
Please start releasing versions. This is nuts. This is now pretty much the de-facto implementation yet packaging it for distros and supporting changes in 3rd party tooling (such as editor plugins) is bizarrely hard.

@ZweiEuro It looks from that version like you're on Arch‌ Linux with has that commit (circa January 6th) as their current packaged version. I'm flagging that as out of date now, but convincing them to update to non-tagged releases is not easy because of the difficulty verifying compatibility.

**Comment by masatake** [comment]
> See also #1038 that seems to be the long-running place this is being tracked.

Yes, #1038 is the place for the topic. Not here.
