### ISSUE TITLE
version 0.0.20190412

### ISSUE THREAD

**Issue by MohamedAhmedAliGpaly** [universal-ctags/ctags#2719]
Hello, can I have a version 0.0.20190412 ?
I building termux-packages/packages/ctags/build.sh ( Last Version p5.9.20201115.0) 
https://github.com/termux/termux-packages/blob/master/packages/ctags/build.sh
But I get the following problem

packcc: Cannot open file 'peg/varlink.peg' to read
make[2]: *** [Makefile:5188: peg/varlink.c] Error 2
make[1]: *** [Makefile:4380: all-recursive] Error 1
make: *** [Makefile:1135: all] Error 2

**Comment by AmaiKinono** [comment]
> I building termux-packages/packages/ctags/build.sh ( Last Version p5.9.20201115.0)
> https://github.com/termux/termux-packages/blob/master/packages/ctags/build.sh

Can I hear how are you using that script? I happen to have termux on my phone, and I tried to install ctags in it (by `pkg install ctags`). I've got some errors, but not the same as yours.

I think it may be better to report this to the package maintainers of termux. The p5.9.20201115.0 version builts fine on my PC, and we have CI to make sure ctags builts on major platforms, so it's likely not a problem of u-ctags.

> can I have a version 0.0.20190412 ?

I'm afraid not. I assume you are asking for a binary. One problem is a binary "built by hand" is not like to work on your architecture and your system library versions (that's why termux offer you an official software repo), another problem is you shouldn't trust us (that's why most if not all software repos have things like chain of trust, verification...)

Or maybe you can try to build ctags on your phone? Our instructions in `docs/autotools.rst` can be a reference.

**Comment by masatake** [comment]
This may be related to #2747.
After merging #2747, we have to talk to people at https://github.com/termux/termux-packages.

**Comment by masatake** [comment]
> I think it may be better to report this to the package maintainers of termux. 

I think so, too.
@leleliu008 solved the issue about cross-compilation in #2747. So the package maintainers can improve their script for building ctags with the changes introduced via #2747. We described newly introduced variables for cross-compilation in https://docs.ctags.io/en/latest/autotools.html#cross-compilation.
