### ISSUE TITLE
Ctags refuses to output line numbers when json-format is activated (Windows 10)

### ISSUE THREAD

**Issue by gneb-io** [universal-ctags/ctags#2792]
When I issue the following command:

    ctags -R --output-format=json --excmd=number -f tag.tg

Ctags stubbornly refuses to output the line numbers. When I remove the `--output-format=json` option, the line numbers magically appear.
I've described the issue also on StackOverflow: https://stackoverflow.com/questions/47811448/ctags-is-stubbornly-refusing-to-print-line-numbers?noredirect=1#comment82585248_47811448

**Comment by masatake** [comment]
Reproduced in both the json and xref output format.

We should fix the ctags itself or write this behavior as the specification of ctags in ctags.1.
I think the latter action is acceptable because users can print the line numbers with --fields=+n (or --_xformat="...%n") as written as an answer on the StackOverflow page.

**Comment by hirooih** [comment]
This issue was fixed in #2859.
