### ISSUE TITLE
R,R6Class: jump to anonFunc####

### ISSUE THREAD

**Issue by kklot** [universal-ctags/ctags#2823]
Sorry if I missed the docs, I have an R6 object in `R` which have methods defined inside a list, and I have the same methods written in `C++` classes. `ctags` generated both `R` and `C++` method but the R one is named with `anonFuncxxx`, which I cannot jump to and not found when e.g. using `fzf` search (in `Vim`), e.g.

```R
|240  anonFunc75e1a69f0103  GitHub/eppasm/R/infections.R  /^infect_mix = function(hivpop, artpop, ii|
```

```C++
|2399 infect_mix  GitHub/eppasm/src/infectionProcesses.cpp  /^void popC::infect_mix (hivC& hivpop, a| 
```

how could I jump to the R's one using its name?

**Comment by masatake** [comment]
I wrote R6 parser. It should extract infect_mix. I wonder why it didn'.t
Could you show me the original R input file (GitHub/eppasm/R/infections.R) ?
The built-in eye-grep cannot find `infect_mix` in https://github.com/mrc-ide/eppasm/blob/master/R/infections.R .

**Comment by kklot** [comment]
could you try with my fork at kklot/eppasm@mix_kincrr

**Comment by kklot** [comment]
the parser does find it but was named with anonFunc. All the R6 methods are like this, which is kind of correct. I'm just unsure how to treat those.

**Comment by masatake** [comment]
Reproduced with https://github.com/kklot/eppasm/blob/1988/R/popClass.R.
At least 2 bugs are there.

**Comment by kklot** [comment]
I see C and Python mentions of this, don't know what that means https://github.com/universal-ctags/ctags/search?q=anonFunc

**Comment by masatake** [comment]
See https://docs.ctags.io/en/latest/man/ctags.1.html#tags-file-contents-options about the anonymous tags.

The anonymous tags are for making names like function having no name `function(hivpop, artpop, ii`.
What you want is `infect_mix`. ctags couldn't make a tag for it because it is not a variable.
I inspected the input source file, and I found it is a name attribute defined in a vector.
```R
popFunc <- c(...
...
}, 

infect_mix = function(hivpop, artpop, ii) {
    ts <- (year-2)/DT + ii
...
```

In #2825, I extended the R parser to support name attributes. As I showed in the initial comment in #2825, ctags can tag `infect_mix` as name attribute. If you know well about git, you can try the improved parser. If you don't, you have to wait till I merge the changes in the pull request. R parser becomes too complicated. So I will not merge the pull request till I find the time for writing the man page for the parser. It will take a long time.
