### ISSUE TITLE
Configuration files called `.ctags` are ignored

### ISSUE THREAD

**Issue by ssiccha** [universal-ctags/ctags#2936]
In the `FILES` section of the man page [ctags(1)](https://docs.ctags.io/en/latest/man/ctags.1.html#files) the possible locations for configuration files all end in `/*.ctags`, for example `$XDG_CONFIG_HOME/ctags/*.ctags`. To me this suggests, that a configuration file could also simply be called `.ctags`, and be placed for example at the location `$XDG_CONFIG_HOME/ctags/.ctags`.

However, when I do that and define a custom language in that file, `GAP` in my case, that custom language is not listed in `ctags --list-languages`. When I save the same file under `$XDG_CONFIG_HOME/ctags/gap.ctags` the language `GAP` does appear in the output of `ctags --list-languages`.

My output of `ctags --version` is
```
Universal Ctags 5.9.0(p5.9.20201227.0), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Dec 27 2020, 09:03:19
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml, +packcc
```

P.S.: Thanks for the amazing tool!

**Comment by masatake** [comment]
`$XDG_CONFIG_HOME/ctags/.ctags` is not acceptable. Could you try `$XDG_CONFIG_HOME/ctags/foo.ctags`?

**Comment by masatake** [comment]
(BTW, I cannot find a test case for `$XDG_CONFIG_HOME/ctags/.ctags` in Tmain. A test case must be added.)

**Comment by masatake** [comment]
`*.ctags` doesn't include `.ctags`. `gap.ctags` is the suitable name for the file that is for paring GAP code. 

Universal Ctags may never load .ctags.
.ctags implies a configuration file.
foo.ctags implies a script for ctags interpreter.

---

I will show the perfect way to solve the issue.

0. let LANG = gap
1. name the file $LANG.ctags,
2. improve $LANG.ctags as much as possible,
3. submit $LANG.ctags as a pull request to Universal Ctags project,
   (Universal Ctags has a translator that converts $LANG.ctags to $LANG.c. So integrating your .ctags to ctags is easy.)
4. I will merge your pull request,
5. I will ask you to be maintainer of the parser.
6. Univeral Ctags including your $LANG.ctags is available widly,
7. You can remove $LANG.ctags from your home directory because Universal Ctags can parser $LANG now.

Some of parsers of ctags are written in this way.
