### ISSUE TITLE
E259: not find ***

### ISSUE THREAD

**Issue by ltang666** [universal-ctags/ctags#3193]
Want to find the definition, but ctags return E259. How can I debug it?

The command line you used to run ctags:
```
ctags -f "/.cache/tags/data.tags.temp" "-
-options=/.vim/plugged/vim-gutentags/res/ctags_recursive.options"  --fields=+niazS --extra=+q --c++-kinds
=+px --c-kinds=+px --output-format=e-ctags "/search/z"
```

The version of ctags:
```
$ ctags --version
Universal Ctags 5.9.0(p5.9.20211114.0), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Nov 16 2021, 14:19:34
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +gnulib_regex, +iconv, +option-directory, +packcc, +optscript
```

How do you get ctags binary:
(
Building it locally, via GNU/Linux distribution
)

vim --version
`VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov 13 2021 20:01:41)
Included patches: 1-3588`

**Comment by masatake** [comment]
What is E259?

Are you talking about the exit status of the ctags process?
If the VIM reports #529, I have no idea.

**Comment by masatake** [comment]
https://stackoverflow.com/questions/15083272/cscope-shows-error-after-using-vim-keyboard-maps

**Comment by masatake** [comment]
It seems that E259 is reported by VIM.
> Want to find the definition, but ctags return E259. How can I debug it?

What you have to do for debugging ctags is find a way to explain the bug of ctags without VIM.

The definition you are looking for is included in tags output of ctags?
If the answer is yes, I would like to say ctags works fine. You cannot debug ctags because ctags has no but about the input files and the definition you are looking for.

If you cannot find the definition in the tags file, there can be a bug of ctags.
You must identify the input file name where the definition is. If the programming language used in the input file is not supported in ctags, the debugging is not needed. Instead, you have to write a new parser. We don't call "writing new parser" is "developping".
