### ISSUE TITLE
Implementing parser with flex/bison

### ISSUE THREAD

**Issue by jafl** [universal-ctags/ctags#3356]
How do you feel about using flex/bison to implement a parser, instead of writing a custom one from scratch?

**Comment by masatake** [comment]
I have been thinking about this topic for a long time.

The benefit is so obvious. So I would like to write about the various reasons we have not introduced flex/bison.

A. the build system becomes more complicated.
B. the way to make the grammar for a language relax is not clear to me.
  ctags used in some editors/IDE (client tools). The developer of client tools may expect ctags to accept broken input.  If a parser is written from scratch, I guess it is more controllable whether the parser accepts broken input or not.
C. Copyright of grammar. We can find a grammar file distributed under a non-GPL compatible license.
  I guess we will receive a pull request based non the grammar file. The potential contributor may include the grammar file to the pull request instead of writing/developing the grammar file. If the grammar file is written by the contributor, there is no issue. If it is taken from somewhere, I have to verify its origin and license clear. I don't want to take much time for the verification. (However, I have to note a great contributor did excellent work. See the discussion in the pull request for merging our kotlin parser.) 

I introduced packcc, a PEG-based parser generator to our build system.
About A, with the help of the other developers, I extended our build-system for supporting packcc.

You can introduce flex/bison to ctags as far as
<a>. you have a plan to write more than two parsers with flex/bison,
<b>. you will drive the tasks extending the build-system to supporting flex/bison, and
<c>. you will develop a utility-layer(?) that helps writing a parser with flex/bison.

About packcc, I wrote peg/peg_common.h for <c>.

I can explain the policy in other words.

Introducing flex/bison is not acceptable just for implementing a parser for a language you are interested in.
I would like to search "Vala" in our issues.

If you have visions/ideas/passion for improving ctags wider area/various aspects (> just improving a parser for a language), I cannot stop you from introducing flex/bison to ctags:-P

**Comment by jafl** [comment]
Thank you for the detailed answer!  I will keep this in mind.
