### ISSUE TITLE
How to communicate?

### ISSUE THREAD

**Issue by ffes** [universal-ctags/ctags#344]
The GitHub issues and PR are not the best way (IMHO) to discuss more general things about the project. So I think we need a way to communicate with each other.

There are a number of options:

1. A mailing list. Can be hosted on https://groups.google.com or on http://www.freelists.org and probably other free services do exist.
2. Forum, hosted somewhere. Haven't found a free host yet
3. IRC. Freenode or OFTC are well known IRC servers.
4. Webbased chat service, like https://gitter.im or another similar service.

I personally prefer the mailing list. Although not perfect, it still seems the best solution to me at the moment. It works great off-line, easy to read back. Different discussions go into separate threads. And speaking for myself, I know I will forget to check a webbased service after a while and miss the important things. So getting the messages in my inbox works for me.

Or maybe I am wrong and we just use issues to discuss things. But then we need to mark as such and close after a certain time of inactive discussion

**Comment by blueyed** [comment]
I personally don't like mailing lists too much, but that's caused by using Gmail for them (where your own posts don't show up) and the subscription process.
But for projects you are more involved in this is not a problem. So +0 to that.

Using Github issues and pull requests seems to be working good so far though, so maybe not scatter it too much for now.

IRC seems a good idea anyway, I'd prefer Freenode.

**Comment by cweagans** [comment]
For mailing lists, +1 for http://librelist.com/. Much easier to get started and view archives than most services. Google Groups is a pain.

**Comment by vhda** [comment]
Since I don't have much available time to invest in the communication, Github issues are still the best solution for my workflow:

1. All communication is centralized in a single platform.
2. Communication is fully registered and can be consulted later.
3. I can contribute whenever I find 5mn to spend reading the updates.

**Comment by masatake** [comment]
I have wanted a mailing for long time. However, nowaday I recognized I am not so young; will not be able to reply timely. For a while I would like to use only github facility.

**Comment by ffes** [comment]
OK, let's stick with github issues for the time being. I've added a "general discussion" label so we can mark issues like this one and close after them after a period of inactivity.

@blueyed I have tried to join the #ctags channel on freenode, but something strange happened. The channel won't stick in Quassel, but all other channels do stick. Is that a Quassel problem on my side, or did you do something special to that channel?

**Comment by blueyed** [comment]
@ffes 
I've not done anything special to the channel (AFAIK).
What do you mean with "stick" in that context?

**Comment by ffes** [comment]
In Quassel on the left is the tree with channels I have joined on the various networks. When I join a channel either by `/join #ctags` or with the dialog in the program the channel is added to the tree. The next time I start Quassel it remembers my channels and rejoins all of them. the ctags channel is not added to the tree and not not remembers.

But it works as expected at home, so it has to be something local on my laptop at the office. So never mind, it is just me.
