### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by listeningwing** [universal-ctags/ctags#4073]
using mmap for performance.

**Comment by masatake** [comment]
A pull request with the results of benchmarks is welcome.
I don't think the ideas improve the performance that can be measured with time command.

a. Nice or renice commands may be what you want (if you use GNU/Linux).

b. If you use glibc, you can ask `fopen` to use mmap internally by specifying `m`. See https://sourceware.org/glibc/manual/2.40/html_node/Opening-Streams.html . However, I don't expect any performance improvement because in most cases, ctags access input files sequentially. The buffer behind `fopen` and `fgetc` may work as if we use mmap.

**Comment by masatake** [comment]
An article [read(2) vs mmap(2) の迷信](https://www.allbsd.org/~hrs/blog/2017-01-02-read-mmap.html) written in Japanese helps us think about the b.
