### ISSUE TITLE
I create a github wiki for this project

### ISSUE THREAD

**Issue by cztchoice** [universal-ctags/ctags#437]
the wiki content is from the docs folder

You can see it here:
https://github.com/cztchoice/ctags/wiki

Do we need this? If it does, I can move it to the project's wiki.

**Comment by masatake** [comment]
First of all, thank you.
I would like to know your intention more.

Do I have to update the contents on the wiki page?
I don't want to do it. I would like to use regular files.

**Comment by cztchoice** [comment]
Github wiki is just a git repo. You can just clone pull push like regular files (The difference may be you need another git repo.

**Comment by cztchoice** [comment]
I think github wiki has following advantages:

* easy to review and maintain (don't need fork and pull request and interrupt the develop log, also we can set the permissions).
* Files in doc dir aim to generate pdf, make it hard to read online. The wiki pages is easy to read.

Besides, I think we should put the development docs (like testing related docs) online. And put user docs in doc folder.

**Comment by masatake** [comment]
This is the second time receiving such offering.
See #353 about my position.

Generally, I commit both docs/*.rst and *.c at once because they are related to each other.
If a repository is splitted into two, one for code and one for docs. I have to commit the changes separately.

Many of parts of docs/*.rst are maintained by me. So I think it is o.k. to make the working flow of documentation is optimized to me.

I don't get much feed back about docs/*.rst so I cannot say good or bad about your offering. 
BTW, with make html, you can generate html files from docs/*.rst.

Making the document online with following conditions is preferrable:
1. My workflow, committing the changes of docs/*.rst to the current git repository, and
2. The commited result is appeared on https://ctags.io.

**Comment by masatake** [comment]
Is it possible the discussion and offering into two?

1. making docs/*.rst online
2. updating working flow

About 1., I'm looking for something better. Your page looks nice. I would like to see it on https://ctags.io.
About 2., I am satisfied with current work flow.

**Comment by cztchoice** [comment]
How about this:
https://github.com/cztchoice/ctags/tree/master/docs

I rename the universal-ctags.rst to readme.rst (make github show it directly), and link the docs together. 
In this case, you don't need to commit to another repo. But it can not output to pdf directly (This can be resolved by a shell script)

**Comment by masatake** [comment]
Renaming the file is a small thing. Wrting a shell script might not be difficult.
If I follow your advice, how can I see the result of changes?

**Comment by cztchoice** [comment]
What do you mean by "result of changes"?

**Comment by masatake** [comment]
I don't understand the benefit of renaming universal-ctags.rst to readme.rst.
If I rename the file, what happes next?

**Comment by masatake** [comment]
docs/*rst files can be edited via wiki interface?

**Comment by cztchoice** [comment]
When you enter docs folder in github, you can see "universal-ctags hacking guide" right in below, without find universal-ctags.rst and click it.

> docs/*rst files can be edited via wiki interface?

no. Because you don't like to edit in other repo, I think make docs more viewable is a good tradeoff.

**Comment by masatake** [comment]
Oh, I see.
Can I ask you to make a PR?

**Comment by cztchoice** [comment]
Sure, I will do it.

**Comment by cztchoice** [comment]
Done, please see https://github.com/universal-ctags/ctags/pull/440
