### ISSUE TITLE
Will universal-ctags replace exuberant-ctags?

### ISSUE THREAD

**Issue by nelstrom** [universal-ctags/ctags#446]
I am currently working on a revised edition of [Practical Vim](https://pragprog.com/book/dnvim/practical-vim). Today I noticed that [the homepage for Exuberant Ctags](http://ctags.sourceforge.net/), hosted on Sourceforge, has gone offline. That led me to learn of the existance of the universal ctags project, which looks really promising!

There's a tip in my book where I give brief instructions on how to install Exuberant Ctags on Ubuntu and OS X (screenshot below). I'm wondering whether I should update those instructions to reference Universal Ctags instead?

My impression right now is that Universal Ctags is not yet ready and it would be premature to include it in the book. But Exuberant Ctags seems to have passed its 'best before' date, so it would be a shame to keep referencing it in the book. It's a tricky decision!

<img width="717" alt="install-ctags" src="https://cloud.githubusercontent.com/assets/7069/8783203/4637772e-2f12-11e5-9dfc-c1fb5161a5a3.png">

**Comment by cweagans** [comment]
The intent is to provide a modernized version of exuberant ctags with more features and active, community-driven maintainership. Despite not being "production ready" right now, I don't think it's too far off. Do you have a particular timeline that you need to follow for this section of the book? Perhaps we can try to work something out so that we have a tagged release out the door by a certain date?

**Comment by nelstrom** [comment]
If a tagged release could be out of the door in the next two weeks, then I think I'd be able to reference Universal Tags in the next edition of Practical Vim without delaying our publishing schedule. If that's not possible, we might be able to stall for a bit more time. I'll check with my publisher.

**Comment by cweagans** [comment]
@masatake Is it realistic to have a tagged release of universal ctags out the door in the next two weeks?

**Comment by ffes** [comment]
SF is down in static mode and apparently it has been for a [couple of days now](http://www.theregister.co.uk/2015/07/19/sourceforge_storage_fault/).

On the subject, I don't think we will have a release within two weeks. We haven't discussed any form of release yet. And it will be our first release as a project so we have to find a way to get that done. We haven't even discussed what the version number should be: 1.0 (our first release) or 6.0 (being the continuation of Exuberant).
And (at least in the Northern hemisphere) it is vacation season, so don't be surprised if some of us will be AFK during the next period.

**Comment by masatake** [comment]
About parsers universal ctags is really improved and mature.
The problem is in the other part. It is hard to release something in a next two weeks.

We(I?) have never discussed seriously about releasing other than how to embed version number into binary.
None talks about it and I don't want to work on it, nothing happens till now. As I wrote before I don't want to work/talk on it because I have to think about compatibility seriously.

What we need to reelase 6.0 (or 1.0)?

1. Evaluate the feature I added when the project is called fishman/ctags. xcmd and optlib are two of such features. The directory structure of optlib is not decided yet. Most of all features I added are written in somewhere in docs/*.rst.

2. Write about features passed the stage 1. to ctags.1.in. 

3. Fix pending issues in our issue tracker. 

4. Rework on Makefile.in.

I think it will take 3 months to do all; and it requires strong motivation.
Especially step 2., I need help the other members.

I am rather interested in working on sharing parser code with geany.

**Comment by nelstrom** [comment]
Thanks all for your responses. 3 months sounds like a plausible time frame for a first tagged release. At this stage, I don't think I can update Practical Vim to reference Universal Ctags instead of Exuberant Ctags, but I'll keep an eye on this project. When version 6.0 (or 1.0) ships I'll revisit this question.

**Comment by cweagans** [comment]
If you need a technical reviewer, let me know. I'd be glad to help :)

**Comment by nelstrom** [comment]
@cweagans thanks for the offer! I'll be in touch soon.

**Comment by dtikhonov** [comment]
I think the version number should be 6, not 1.

**Comment by masatake** [comment]
I agree with version 6 is better than 1.

**Comment by nelstrom** [comment]
It's that time again: I'm revising [Practical Vim](https://pragprog.com/book/dnvim2/practical-vim-second-edition) to bring it up to date now that [Vim 8.0 has been released](https://github.com/vim/vim/releases/tag/v8.0.0000). As before, I'm considering whether or not it would be appropriate to update the tip on `ctags` to recommend Universal ctags, instead of Exuberant ctags. I see that the project has yet to cut its first release (also discussed in #1038), so my hunch is that it's still too soon.

**Comment by masatake** [comment]
@nelstrom, still far from releasing. tags format issue is not solved yet. This is the critical issue.
Update the man pages and revise the command line interface is the second isssues.

**Comment by nelstrom** [comment]
@masatake ok, thanks for the update!
