### ISSUE TITLE
[Proposal] Arrange compiler/linker option specifings in Makefile.in

### ISSUE THREAD

**Issue by p-montanus** [universal-ctags/ctags#585]
I propose arranging some compiler and linker option specifings in Makefile.in.

Target Makefile.in lines are:
```
SPARSEFLAGS=-Wsparse-all
COVERAGE_CFLAGS=--coverage
COVERAGE_LDFLAGS=--coverage
ALL_CFLAGS = $(CFLAGS) --std=gnu99 -Wall $(COVERAGE_CFLAGS)
```

* `-Wsparse-all`: would be specified via `AC_SUBST([CGCC_CFLAGS])` via  `AC_ARG_VAR([CGCC_CFLAGS])` ~~`AC_ARG_WITH([sparse-warning-flags])`~~ at configure.ac. and also, add `--with-sparse-cgcc` configure option.
* `--coverage` (CFLAGS): would be specified via `AC_SUBST([COVERAGE_CFLAGS])` via `AC_ARG_ENABLE([coverage-gcov])` ~~`AC_ARG_ENABLE([coverage])`~~ at configure.ac.
* `--coverage` (LDFLAGS): would be specified via `AC_SUBST([COVERAGE_LDFLAGS])` via `AC_ARG_ENABLE([coverage-gcov])` ~~`AC_ARG_ENABLE([coverage])`~~ at configure.ac.
* `--std=gnu99`: would be specified via `AC_SUBST([EXTRA_CFLAGS])` via `AC_ARG_VAR([EXTRA_CFLAGS])` at configure.ac.
* `-Wall` would be specified via `AC_SUBST([WARNING_CFLAGS])` via `AC_ARG_VAR([WARNING_CFLAGS])` at configure.ac.

**Comment by steveno** [comment]
:+1:

**Comment by b4n** [comment]
If you do that to improve portability by providing alternative and conditional enabling of those features, why not.  Otherwise, I don't really see the point of the extra complexity.

Basically, for the flags used by all targets, sure it'd be great to check for them (and for C99 use `AC_PROG_CC_C99` obvly), if we mean to support non-GCC compilers through these makefiles (I hope we do, although I wouldn't actually see any difference).
For other targets if there is no replacements it might not be really useful.

Anyway, it basically looks like a good idea, but I'd need to see/think on the resulting changes to see whether I believe all changes are worth the extra code.

**Comment by vhda** [comment]
Just adding something to @b4n 's reply: you can always create a PR instead of an issue. The PR can contain not only the description of your idea, but also its implementation. By having everything in the same place it makes it easier for review. And the worst that can happen is the PR not being merged, right? No harm done! :)

**Comment by p-montanus** [comment]
@b4n
Thank you for your comments.

>If you do that to improve portability by providing alternative and conditional enabling of those features, why not. Otherwise, I don't really see the point of the extra complexity.

Yes, it aims to improve portability and flexibility.

>Anyway, it basically looks like a good idea, but I'd need to see/think on the resulting changes to see whether I believe all changes are worth the extra code.

Excuse me. I will push the proposal branch soon.

**Comment by p-montanus** [comment]
@vhda
Thank you for advising preferred way of proposing.
Next time, I will create a pull request, first.

**Comment by p-montanus** [comment]
proposal branch pushd: p-montanus/ctags@0ed4f862ef84f2503923c720874624cbb5c0e226.

**Comment by b4n** [comment]
> Next time, I will create a pull request, first.

That's good, but if it'll likely be controversial and requires a lot of work you probably still should talk about it first, not to waste your time.  Sure commenting with code often gives a lot more context and details, but wasting time on code that ends up rejected and that don't spawn anything better in the end would also be sad.

**Comment by p-montanus** [comment]
>>Next time, I will create a pull request, first.

>That's good, but if it'll likely be controversial and requires a lot of work you probably still should talk >about it first, not to waste your time. Sure commenting with code often gives a lot more context and >details, but wasting time on code that ends up rejected and that don't spawn anything better in the end would also be sad.

Thank you for giving me guidelines - when/why should (not) create an issue.
