### ISSUE TITLE
make ctags a library

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#63]
"Library" in ctags may have 3 aspects:
1. reading tags file,
2. backend language parser, and
3. running ctags.

The scope is this issue is "3. running ctags."
We have to research Geany.

Decreasing global variables will be the initial step.

**Comment by dtikhonov** [comment]
@b4n, why not `fmemopen(3)` instead of MIO?

**Comment by b4n** [comment]
@dtikhonov Well, first, I didn't know about it :)  Then, and probably a reason why I didn't find about it at the time (2011), it's not very portable (in POSIX.1-2008 but not before, otherwise seems to be `_GNU_SOURCE`).

So it'd be very nice, but I'm really not sure it's an acceptable dependency (would have to be checked on all platforms, also for consistency as if it's pre-POSIX, it's likely to have slight inconsistencies -- and we can't really reimplement it where missing as FILE is totally opaque).

**Comment by elextr** [comment]
@b4n, isn't another reason for not parsing in another thread to prevent having to make a copy of the Scintilla buffer.  ATM the parser blocks Scintilla, so it can't move the buffer (by re-allocating it) or the gap during a parse.

**Comment by masatake** [comment]
libctags.a is introduced. Though it is not a generic library, but I think I can close this now.
Refining the API for Geany is the next step.
