### ISSUE TITLE
Let easytag handle the output pattern "0.0.0" in ctags --version (Was: Version 0.0.0)

### ISSUE THREAD

**Issue by sbuljac** [universal-ctags/ctags#748]
ctags --version 

prints

Universal Ctags 0.0.0(a1c4a13), Copyright (C) 2015 Universal Ctags Team

**Comment by masatake** [comment]
What's wrong?  Should we add 2016?

**Comment by sbuljac** [comment]
I think it was Universal Ctags Development before. 0.0.0 breaks easytag VIM plugin, because it reads a 0.0.0 as version of Exuberant Ctags and wont start...
I understand this is not a bug but it would be nice if everything could work as before...

**Comment by masatake** [comment]
I see.

**Comment by masatake** [comment]
I think improving easytag is much constructive.
If you argue that  it would be nice if everything could work as before, my recommendation is  Exuberant Ctags.

As far as seeing https://github.com/xolox/vim-easytags/commit/72a8753b5d0a951e547c51b13633f680a95b5483 and https://github.com/xolox/vim-easytags/issues/123, fixing easytag will not be difficult. The issue is I'm not vim user, and the easytag
developer doesn't have time to try universal ctags.

**Comment by sbuljac** [comment]
I change version to 5.8  recompiled and everything works for me , no need to go back to Exuberant Ctags... I just thought you should know about this problem because backward compatibility is usually desirable...

**Comment by masatake** [comment]
I will try to fix easytag side. I'm afraid your patch will not work with newer easytag.

**Comment by masatake** [comment]
https://github.com/Wraul/vim-easytags/commit/f5746bdfd9942b00c349e53f3f4917ae73bb6797
