### ISSUE TITLE
Replace m4 parser

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#825]
Replace opt/m4.ctags with better implementation: https://github.com/b4n/geany/blob/wip/master/tagmanager/ctags/m4.c

**Comment by masatake** [comment]
@b4n, I would like to import your m4.c. Can I ask you to make the version of GPL clear?
If you allow, I would like to import it to ctags with "the GNU General Public License version 2 or (at your option) any later version." .

**Comment by b4n** [comment]
@masatake sure, it's now done.

There likely is a typo at https://github.com/b4n/geany/blob/wip/master/tagmanager/ctags/m4.c#L308, I guess I meant ```(c == '"' || c == '\'' || c == '`')```, but I'm not totally sure right now so I didn't change it yet.  Pretty sure though esp. as this happened in a larger change.

**Comment by masatake** [comment]
Thanks. I'm working on parsers for understanding build system and scripts.
Autoconf/m4 parsers are the last pieces.

**Comment by masatake** [comment]
The m4 parser is very interesting. It changes the language/parser dynamically to autoconf parser when the m4 parser finds pattern like AC_. I have to think more to find good way to adapt the parser to universal-ctags.

**Comment by masatake** [comment]
Finally I found a good way.
I will introduce two new functions: pushLanguage and popLanguage.

**Comment by masatake** [comment]
I have a question.

In https://github.com/b4n/geany/blob/wip/master/tagmanager/ctags/m4.c#L328
you calls `skipBlanks`. I think this can be removed because  `readMacroArgument` is called 
in https://github.com/b4n/geany/blob/wip/master/tagmanager/ctags/m4.c#L330.

At the head of `readMacroArgument`, `readMacroArgument` does the same as what `skipBlanks` does.

@b4n, can I ask you give me comments?

**Comment by b4n** [comment]
@masatake you seem to be right indeed.  Also, as it's the only usage of `skipBlanks()`, it could be removed altogether.

**Comment by masatake** [comment]
@b4n, thank you.

**Comment by b4n** [comment]
@masatake fixed in https://github.com/b4n/geany/commit/ce7d77b73f1c71163f3378c5ef7bbd7e3d620735

**Comment by b4n** [comment]
> The m4 parser is very interesting. It changes the language/parser dynamically to autoconf parser when the m4 parser finds pattern like AC_. I have to think more to find good way to adapt the parser to universal-ctags.

BTW, it's not really necessary to do that; the goal was to have 2 different parsers to select initial quote style, and try and be smart about `.m4` files.  However, the parsers could very well not change the language, and that quote style switch be an internal thing only.  With the possibility to manually alter the parser to use for a specific extension a caller could deal with it manually just fine if they want a particular language.

So it would be just fine to not dynamically change the CTags language but just changing an internal flag instead.  It might even make more sense, because it's not really 2 languages nested in each other, but 2 variants of the same language.

**Comment by masatake** [comment]
...I had reworked completely to allow dynamically change.
