### ISSUE TITLE
Generating tags failed when file contains ">>"

### ISSUE THREAD

**Issue by hiberabyss** [universal-ctags/ctags#834]
When there is code like `vector<vector<int>> C;` , then ctags can't generate tags for the codes below that lines.

For file test.cpp:
```
struct A {
	int a;
	int b;
};
``` 
run `ctags test.cpp` will generate following `tags` file:
```
A	test.cpp	/^struct A {$/;"	kind:s	file:
A::a	test.cpp	/^	int a;$/;"	kind:m	struct:A	file:	access:public
A::b	test.cpp	/^	int b;$/;"	kind:m	struct:A	file:	access:public
a	test.cpp	/^	int a;$/;"	kind:m	struct:A	file:	access:public
b	test.cpp	/^	int b;$/;"	kind:m	struct:A	file:	access:public
```

However, for file test1.cpp
```
vector<vector<int>> C;

struct A {
	int a;
	int b;
};
```
after run `ctags test1.cpp`, there is no tag in the `tags` file.

The output after run `ctags --version` is:
```
Universal Ctags 0.0.0(5129760), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Mar 10 2016, 19:27:46
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +option-directory, +coproc, +xpath
```

**Comment by masatake** [comment]
@pragmaware, I tried your latest C++ parser with the input reported by @hiberabyss:

```

[yamato@x201]~/var/ctags-github% cat /tmp/foo.cpp              
#include <vector>
using namespace std;

vector<vector<int>> C;
struct A {
    int a;
    int b;
};
[yamato@x201]~/var/ctags-github% gcc -std=c++11 -c /tmp/foo.cpp           
[yamato@x201]~/var/ctags-github% ./ctags --kinds-C++='*' -o - /tmp/foo.cpp
A	/tmp/foo.cpp	/^struct A {$/;"	s	file:
a	/tmp/foo.cpp	/^    int a;$/;"	m	struct:A	file:
b	/tmp/foo.cpp	/^    int b;$/;"	m	struct:A	file:
std	/tmp/foo.cpp	/^using namespace std;$/;"	U	file:
```
It seems that the original bug reported by @hiberabyss is fixed in your parser.
However, C is not appearted on the tags file. Could you fix this?

I guess this is fundamental limitation of single pass parser.

**Comment by masatake** [comment]
@hiberabyss, thank you for reporting.
Currently @pragmaware is working hard to rewrite C/C++ parser of universal ctags.
Testing and reviewing are conducted in #824. As far as I tried, the bug your reported is fixed already in the new parser. However, as I found another issue.

**Comment by pragmaware** [comment]
Technically that's a syntax error.

input.cpp:14:18: error: ‘>>’ should be ‘> >’ within a nested template argument list
    vector<vector<int>> C;

Since in this instance there is a keyword before the >> (which is a shift operator) I can probably add a special case in the code to handle the syntax error and emit the tag anyway...
...but do you think it's a good idea?

**Comment by masatake** [comment]
> Technically that's a syntax error.

As far as giving the input to gcc, gcc accepts only if  `-std=c++11` is given.

> where 'someType' is not a keyword. This is because
>
>int vector;
>int someType;
>int C;
>vector < vector < someType >> C;
>
>is a valid C++ statement (which does not define a variable).

Oh, I see. As you may know very well, people have strong interest C++ support in ctags (so that you are here :-P). The number of issues opened these days tells it. I guess we will get more. Further more the may of them about template. I would like to ask you to write entries for FAQ? If you can, I will prepare faq.rst under docs dir.

**Comment by pragmaware** [comment]
Right. I will support this syntax then.

**Comment by masatake** [comment]
@hiberabyss, as I wrote a bug you reported is already fixed in the new C++parser @pragmaware is working on. So we will fix this case when the new parser is merged as default C/C++ parser of universal-ctags.

As we discussed, there may be fundamental technical limit in tagging C on the example input.
Feel free to give us comments. @pragmaware will decide the direction of the parser with reflecting the comments from users like you.

**Comment by pragmaware** [comment]
Done :)

**Comment by hiberabyss** [comment]
@masatake @pragmaware , thanks very much for your amazing work!  The main problem caused by `vector<vector<int>> C;` is that it will block generating tags for the lines following it in the same file. I think it's ok that don't generate tag `C` if much work needed and can't be applicable for many cases.

**Comment by masatake** [comment]
The new parser is merged.
