### ISSUE TITLE
Provide the way to define parser own options

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#841]
What kind of option format do you want?

My idea:

```
--opt-<LANG>=<OPT>:<VALUE>
```

**Comment by pragmaware** [comment]
Mh... maybe for simplicity the parser specific options could be stored in the global options structure.
We could just define a policy for naming as --<LANG>-<OPTION>:

   --c++-preserve-templates
   --python-something=value
   --c-do-something=value
  etc...

so basically no additional per-parser code would be needed ?

**Comment by masatake** [comment]
The language common prefix is needed two reasons.

* Consider language named "help" as an example. 
   Without the prefix, we have to introduce `--help-something=value`.
    Users and we will be confused. 
    The name of language is obviously wrong but we cannot choose the name of language.

   This is the reason why I introduced `--kind-<LANG>` option.

* I have nerver tried implementing but I guess the common prefix will make implementing bash/zsh completion rules for ctags easier.

How about `-O <LANG>-something=value` or `-O <LANG>:something=value` ?

**Comment by pragmaware** [comment]
Hm.. we already have --<LANG>-kinds.

One point I would like to throw in is that the ctags options are already quite complex and hard to use. It took me quite a while and a lot of man page readings to understand how to use kinds, fields, extras etc.
We should avoid to increase the complexity further more...

**Comment by masatake** [comment]
> Hm.. we already have --<LANG>-kinds
I would like to remove `--<LANG>-kinds`. However, it breaks compatibility.

> One point I would like to throw in is that the ctags options are already quite complex and hard to use. It took me quite a while and a lot of man page readings to understand how to use kinds, fields, extras etc.
We should avoid to increase the complexity further more...

Comparing following two:
```
--c++-preserve-templates
```
```
-O C++:preserve-templates
```
The former will be listed in `--help`.
The later will be not. Just `-O` is listed but `C++:preserve-templates` is not.
`preserve-templates` will be listed in ``--list-parser-option=C++``.

I think the later is a bit simpler than the former in this aspect.

**Comment by pragmaware** [comment]
Hm... don't know.

(in favor of --c++-preserve-templates)
Using more commands to figure out options looks more complex to me.
--c++-preserve-templates=value is quite standard (and you will find it directly in the --help output).
-O C++:preserve-templates=value is not really standard and one will first have to discover it by stumbling upon --list-parser-options and then memorize how to use it by repeatedly looking at --help

(in favor of -O c++:preserve-templates)
On the other side --<LANG>-<option> will probably clutter --help a lot, making it harder to read.
Once learned --list-parser-options=C++ is faster to use since it will directly output the options you want to see.

Not sure which one to choose. Probably the one that looks more promising/easy/appealing from the implementation point of view?

**Comment by masatake** [comment]
From the implementation point of view,  `-O` is better.

`-O` will be handling at main/option.c. The name of parameter and its value is passed to a parser.
A parser should declare what kind of parameter does it take. The responsibilities between a parser and main part are well separated  here.

It is very similar to processing `--kind-<LANG>=+X`. Extracting `<LANG>` and `X` from the command line is the job of main part. A parser declares what kind of kind does it take.

**Comment by masatake** [comment]
`--param-<LANG>:<NAME>=<VALUE>` was introduced.
