### ISSUE TITLE
Include s: prefix with vim

### ISSUE THREAD

**Issue by blueyed** [universal-ctags/ctags#852]
I think that the `s:` prefix for functions should be kept for Vim files:

Currently it gets parsed like this:

    ext.add_inactive_statusline_func autoload/airline/extensions.vim /^function! s:ext.add_inactive_statusline_func(name) dict$/;" f language:Vim

The `s:` prefix is useful to know about, and is also actually required when calling the function.

**Comment by masatake** [comment]
What does the `s:` mean?

**Comment by blueyed** [comment]
From `:h :s`:

```
						*script-variable* *s:var*
In a Vim script variables starting with "s:" can be used.  They cannot be
accessed from outside of the scripts, thus are local to the script.

They can be used in:
- commands executed while the script is sourced
- functions defined in the script
- autocommands defined in the script
- functions and autocommands defined in functions and autocommands which were
  defined in the script (recursively)
- user defined commands defined in the script
Thus not in:
- other scripts sourced from this one
- mappings
- menus
- etc.
```

Other prefixes are `g:` (global), `l:` (local), `t:` (tab page), `w:` (window), `b:` (buffer) etc:

```
		(nothing) In a function: local to a function; otherwise: global
|buffer-variable|    b:	  Local to the current buffer.
|window-variable|    w:	  Local to the current window.
|tabpage-variable|   t:	  Local to the current tab page.
|global-variable|    g:	  Global.
|local-variable|     l:	  Local to a function.
|script-variable|    s:	  Local to a |:source|'ed Vim script.
|function-argument|  a:	  Function argument (only inside a function).
|vim-variable|       v:	  Global, predefined by Vim.
```

For functions, only `s:` is relevant (AFAIK).

**Comment by masatake** [comment]
It seems that `s:` is something like `static` modifier in C language. Am I correct?

**Comment by vhda** [comment]
Not exactly. In the same .vim file (referred to above as "script") you can declare two functions with the name but with different scopes, as in:

```vim
function Test()
  call s:Test()
endfunction

function s:Test()
endfunction
```

`Test()` is a global function that can be called from everywhere, while `s:Test()` is only available inside the script (.vim) file where it is declared. (This last bit is not _exactly_ true, but it serves the purpose for this explanation).

**Comment by masatake** [comment]
@vhda, I see.  Let's think about the input.
Currently we got(the current output):

```
Test	/tmp/foo.vim	/^function Test()$/;"	f
Test	/tmp/foo.vim	/^function s:Test()$/;"	f
```

How about following output(new output)?
```
Test	/tmp/foo.vim	/^function Test()$/;"	f
Test	/tmp/foo.vim	/^function s:Test()$/;"	f	prefix:s
```
or
```
Test	/tmp/foo.vim	/^function Test()$/;"	f
Test	/tmp/foo.vim	/^function s:Test()$/;"	f	prefix-long:script-variable
```

Do you think the new output is better than current output?

Adding 's:Test' as an entry will be ideal for you. However, I think it is similar to full qualified name;
ctags can add `s:Test` to tags file but only when --extra option is given.

**Comment by vhda** [comment]
Unfortunately, Vim is very limited in how it processes the tags file, so the solution you are proposing will not help Vim users because the extra attributes are not used. So, to navigate to the declaration of `s:Test` Vim requires that a tag with the exact same name exists. In fact, if you look at how variables are currently processed in ctags you will see that they will keep the `s:` prefix.

As @blueyed proposed initially, I think we should simply keep this prefix in functions as we already do in variables.

**Comment by masatake** [comment]
> Unfortunately, Vim is very limited in how it processes the tags file, so the solution you are proposing will not help Vim users because the extra attributes are not used. So, to navigate to the declaration of s:Test Vim requires that a tag with the exact same name exists.

This is not enough reason to add `s:` to names by default. Vim should be fixed or use --extra option to generate tags files suitable for vim.

>  In fact, if you look at how variables are currently processed in ctags you will see that they will keep the s: prefix.

This is enough reason to add `s:` prefix to function. 

> As @blueyed proposed initially, I think we should simply keep this prefix in functions as we already do in variables.

Basically I agree with you.

**Comment by masatake** [comment]
I guess solving this is not easy for the one who knows the syntax of vim script.
However, I would like to solve #861 first.

**Comment by fourjay** [comment]
Can you add an option to revert this behavior?
"s:" is a scope local tag, but one of it's common usages is with a "<SID>"  prefix. The scenario:
1) Script is locally defined
2) But is added to a mapping, as in
``noremap <C-J> <SID>do_something()``
This allows the locally created and visible script to be accessible outside the script in a global mapping but not be visible otherwise.
Current behavior breaks tags in that scenario where older behavior handles this correctly.
FWIW, I started to add workarounds for this, in particular adding ``iskeyword+=:`` to vimscript files and replacing unneeded ``<SID>`` prefixes with ``s:`` prefixes. But now I'm faced with adding additional pattern rules to recreate the old behavior to allow ``<SID>`` to work. This requested change seems to involve more work to adjust then such a change should. It used to "just work" and now requires significant adjustment in workflow. 
If nothing else, I'd appreciate a walkthrough in the docs (in particular the incompatibility note) about how to work around the changes

**Comment by blueyed** [comment]
@fourjay 
Thanks for bringing that up.

Could we add maybe `s:` and `<SID>` variant to the tags file then?  I.e. for `s:foo` there would also be an entry (alias) `<SID>foo`?
But then it's probably still a matter of if it gets matched by `<SID>`, right?
Or have it with the `s:` prefix and without?

**Comment by dkearns** [comment]
Simply reverting this change doesn't seem like the right fix as the original behaviour was inconsistent even if it worked for the given use-case.  However, I think the current approach is also wrong and tend to agree with @masatake 's original suggestion.

The scope prefixes (name spaces) should just be recorded in the appropriate field by default. The tags file can then be generated with --extra=+q to explicitly add fully qualified variable names if desired.

It's uncommon for there to be much variable 'shadowing' used in VimL so I expect a prefix-free tag list will mostly work as desired from within Vim anyway without too many multiple matches.

The current format requires  the user to modify 'iskeyword' which is generally a bad idea as too many of the support files rely on it.  This situation will be a little better in Vim 8 with the syntax-local iskeyword but I expect it will still cause problems.

@fourjay, I currently use a remapped <C-]> to extract/create the appropriate identifier (setting/unsetting 'isk' and checking for and substituting "<SID>" with "s:").
