### ISSUE TITLE
reuse stream opend in language guessing stage

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#874]
A file is opened in language guessing stage. 
However, it is not used in main parsing stage; the stream opened in guessing stage is closed after guessing.
The stream is reopened before main parsing stage.

After adding refcount field to mio object, I think the stream(mio object) can be share the both stage.

**Comment by techee** [comment]
The problem I see is that when loading the file into MIO the whole file is read (because the whole file will be parsed). However when guessing the file type this could be a waste of time because if it's determined that the file cannot be parsed with ctags because it's not a supported file type, there's no need to read the whole file.
